services:
  chrome-vnc:
    #build: .
    image: chrome-vnc:20260615
    container_name: chrome-vnc
    init: true
    # 增加共享内存，防止 Chrome 崩溃 (1GB 或更高)
    shm_size: '2gb'
    ports:
      - "6080:6080" # noVNC 网页桌面 (需 Basic Auth: admin/你的密码)
      - "5900:5900" # 原生 VNC 端口
      - "9222:9222" # Chrome CDP 远程调试代理端口
    environment:
      - VNC_PASSWORD=mEwXllS7gJu5bOGzEz8JdPJ1Ibz
      - RESOLUTION=1440x2048x24
    restart: unless-stopped